name: Build

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build:
      name: Build solution
      uses: ads102003/Actions/.github/workflows/project-build.yml@main
      with:
        branch-postfix: ${{ github.ref_name }}
        version-prefix: '2.0'
        project-name: Oxide.CSharp
      secrets: inherit
